export const DEFAULT_KPI_360_ITEMS = {
  store: [
    {
      item_key: 'kerjasama_tim',
      item_name: 'Kerjasama Tim',
      description: 'Mau membantu rekan, tidak egois, solid saat sibuk',
      score_1: 'Tidak pernah membantu',
      score_2: 'Jarang membantu',
      score_3: 'Cukup kooperatif',
      score_4: 'Kooperatif',
      score_5: 'Sangat solid & proaktif membantu',
      sort_order: 1,
    },
    {
      item_key: 'komunikasi_sikap',
      item_name: 'Komunikasi & Sikap',
      description: 'Cara bicara, bahasa tubuh, respek ke sesama rekan',
      score_1: 'Sering konflik atau kasar',
      score_2: 'Kurang sopan',
      score_3: 'Cukup baik',
      score_4: 'Komunikatif & sopan',
      score_5: 'Sangat positif & memotivasi',
      sort_order: 2,
    },
    {
      item_key: 'inisiatif',
      item_name: 'Inisiatif & Proaktif',
      description: 'Bertindak tanpa harus disuruh, cari solusi sendiri',
      score_1: 'Tidak pernah inisiatif',
      score_2: 'Jarang inisiatif',
      score_3: 'Kadang inisiatif',
      score_4: 'Sering inisiatif',
      score_5: 'Selalu proaktif',
      sort_order: 3,
    },
    {
      item_key: 'kedisiplinan',
      item_name: 'Kedisiplinan',
      description: 'Tepat waktu, sesuai jadwal, tidak sering izin mendadak',
      score_1: 'Sangat tidak disiplin',
      score_2: 'Kurang disiplin',
      score_3: 'Cukup disiplin',
      score_4: 'Disiplin',
      score_5: 'Sangat disiplin & jadi contoh',
      sort_order: 4,
    },
    {
      item_key: 'tanggung_jawab',
      item_name: 'Tanggung Jawab Kerja',
      description: 'Menyelesaikan tugas, tidak lempar tanggung jawab',
      score_1: 'Sering tidak selesai',
      score_2: 'Sering tidak tuntas',
      score_3: 'Kadang tidak tuntas',
      score_4: 'Selalu tuntas',
      score_5: 'Sangat bertanggung jawab & bisa diandalkan',
      sort_order: 5,
    },
  ],
  manager: [
    {
      item_key: 'kepemimpinan',
      item_name: 'Kepemimpinan & Pengambilan Keputusan',
      description: 'Tegas, adil, dan cepat dalam mengambil keputusan',
      score_1: 'Tidak mampu memimpin',
      score_2: 'Kurang tegas',
      score_3: 'Cukup baik',
      score_4: 'Tegas & adil',
      score_5: 'Inspiratif & visioner',
      sort_order: 1,
    },
    {
      item_key: 'komunikasi_arahan',
      item_name: 'Komunikasi & Arahan',
      description: 'Instruksi jelas, tidak ambigu, mudah dipahami tim',
      score_1: 'Tidak jelas sama sekali',
      score_2: 'Sering ambigu',
      score_3: 'Cukup jelas',
      score_4: 'Jelas & terstruktur',
      score_5: 'Sangat jelas & efektif',
      sort_order: 2,
    },
    {
      item_key: 'coaching_tim',
      item_name: 'Coaching & Pengembangan Tim',
      description: 'Aktif membimbing, memberi feedback, dorong pertumbuhan',
      score_1: 'Tidak pernah coaching',
      score_2: 'Jarang coaching',
      score_3: 'Kadang coaching',
      score_4: 'Rutin coaching',
      score_5: 'Sangat aktif & berdampak',
      sort_order: 3,
    },
    {
      item_key: 'integritas',
      item_name: 'Integritas & Konsistensi',
      description: 'Konsisten antara ucapan dan tindakan, jujur, bisa dipercaya',
      score_1: 'Sering tidak konsisten',
      score_2: 'Kurang konsisten',
      score_3: 'Cukup konsisten',
      score_4: 'Konsisten',
      score_5: 'Sangat integritas & jadi teladan',
      sort_order: 4,
    },
    {
      item_key: 'kolaborasi',
      item_name: 'Kolaborasi Antar Divisi/Toko',
      description: 'Terbuka bekerja sama lintas toko atau divisi',
      score_1: 'Sulit diajak kolaborasi',
      score_2: 'Jarang terbuka',
      score_3: 'Cukup kolaboratif',
      score_4: 'Kolaboratif',
      score_5: 'Sangat kolaboratif & menyatukan tim',
      sort_order: 5,
    },
  ],
}

export const DEFAULT_KPI_PERSONAL_ITEMS = {
  barista: [
    { item_key: 'checklist_completion', item_name: 'Checklist Harian - Completion Rate', target: '>=90%', contribution: 13, cara_penilaian: 'Auto dari daily_checklists (shift yang ditugaskan)', source_type: 'auto_checklist', score_1: '<60%', score_2: '<70%', score_3: '<80%', score_4: '<90%', score_5: '>=90%', sort_order: 1 },
    { item_key: 'prep_bar_completion', item_name: 'Preparation Bar - Completion Rate', target: '>=90%', contribution: 13, cara_penilaian: 'Auto dari daily_preparation section Bar', source_type: 'auto_preparation', score_1: '<60%', score_2: '<70%', score_3: '<80%', score_4: '<90%', score_5: '>=90%', sort_order: 2 },
    { item_key: 'kualitas_minuman', item_name: 'Kualitas Minuman', target: 'Sesuai SOP', contribution: 18, cara_penilaian: 'Penilaian Head Store (rasa, tampilan, takaran)', source_type: 'manual', score_1: 'Tidak sesuai SOP', score_2: 'Kadang tidak sesuai', score_3: 'Cukup sesuai', score_4: 'Sesuai', score_5: 'Sangat sesuai & konsisten', sort_order: 3 },
    { item_key: 'kecepatan_penyajian', item_name: 'Kecepatan Penyajian', target: '<=5 menit', contribution: 13, cara_penilaian: 'Penilaian Head Store (observasi langsung)', source_type: 'manual', score_1: '>8 menit', score_2: '>7 menit', score_3: '>6 menit', score_4: '>5 menit', score_5: '<=5 menit', sort_order: 4 },
    { item_key: 'kebersihan_bar', item_name: 'Kebersihan Area Bar', target: 'Bersih', contribution: 13, cara_penilaian: 'Penilaian Head Store / Audit DM', source_type: 'manual', score_1: 'Sangat kotor', score_2: 'Kotor', score_3: 'Cukup bersih', score_4: 'Bersih', score_5: 'Sangat bersih', sort_order: 5 },
    { item_key: 'waste_spoil_bar', item_name: 'Waste & Spoil Area Bar', target: '0 kejadian', contribution: 10, cara_penilaian: 'LOG Waste dari Head Store', source_type: 'manual', score_1: '>4 kejadian', score_2: '3 kejadian', score_3: '2 kejadian', score_4: '1 kejadian', score_5: '0 kejadian', sort_order: 6 },
    { item_key: 'kedisiplinan', item_name: 'Kedisiplinan & Kehadiran', target: '>=95%', contribution: 10, cara_penilaian: 'Data absensi / catatan Head Store', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=95%', sort_order: 7 },
    { item_key: 'peer_review_360', item_name: 'Penilaian 360° Rekan Kerja', target: '>=4.0', contribution: 10, cara_penilaian: 'Rata-rata skor dari rekan kerja satu toko (anonim)', source_type: 'auto_360', score_1: '<2.0', score_2: '<2.5', score_3: '<3.0', score_4: '<4.0', score_5: '>=4.0', sort_order: 8 },
  ],
  kitchen: [
    { item_key: 'checklist_completion', item_name: 'Checklist Harian - Completion Rate', target: '>=90%', contribution: 13, cara_penilaian: 'Auto dari daily_checklists (shift yang ditugaskan)', source_type: 'auto_checklist', score_1: '<60%', score_2: '<70%', score_3: '<80%', score_4: '<90%', score_5: '>=90%', sort_order: 1 },
    { item_key: 'prep_kitchen_completion', item_name: 'Preparation Kitchen - Completion Rate', target: '>=90%', contribution: 13, cara_penilaian: 'Auto dari daily_preparation section Kitchen', source_type: 'auto_preparation', score_1: '<60%', score_2: '<70%', score_3: '<80%', score_4: '<90%', score_5: '>=90%', sort_order: 2 },
    { item_key: 'kualitas_makanan', item_name: 'Kualitas Makanan', target: 'Sesuai SOP', contribution: 18, cara_penilaian: 'Penilaian Head Store (rasa, tampilan, porsi)', source_type: 'manual', score_1: 'Tidak sesuai SOP', score_2: 'Kadang tidak sesuai', score_3: 'Cukup sesuai', score_4: 'Sesuai', score_5: 'Sangat sesuai & konsisten', sort_order: 3 },
    { item_key: 'kecepatan_penyajian', item_name: 'Kecepatan Penyajian Makanan', target: '<=10 menit', contribution: 13, cara_penilaian: 'Penilaian Head Store (observasi langsung)', source_type: 'manual', score_1: '>15 menit', score_2: '>13 menit', score_3: '>12 menit', score_4: '>11 menit', score_5: '<=10 menit', sort_order: 4 },
    { item_key: 'kebersihan_kitchen', item_name: 'Kebersihan Area Kitchen', target: 'Bersih', contribution: 13, cara_penilaian: 'Penilaian Head Store / Audit DM', source_type: 'manual', score_1: 'Sangat kotor', score_2: 'Kotor', score_3: 'Cukup bersih', score_4: 'Bersih', score_5: 'Sangat bersih', sort_order: 5 },
    { item_key: 'waste_spoil_kitchen', item_name: 'Waste & Spoil Area Kitchen', target: '0 kejadian', contribution: 10, cara_penilaian: 'LOG Waste dari Head Store', source_type: 'manual', score_1: '>4 kejadian', score_2: '3 kejadian', score_3: '2 kejadian', score_4: '1 kejadian', score_5: '0 kejadian', sort_order: 6 },
    { item_key: 'kedisiplinan', item_name: 'Kedisiplinan & Kehadiran', target: '>=95%', contribution: 10, cara_penilaian: 'Data absensi / catatan Head Store', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=95%', sort_order: 7 },
    { item_key: 'peer_review_360', item_name: 'Penilaian 360° Rekan Kerja', target: '>=4.0', contribution: 10, cara_penilaian: 'Rata-rata skor dari rekan kerja satu toko (anonim)', source_type: 'auto_360', score_1: '<2.0', score_2: '<2.5', score_3: '<3.0', score_4: '<4.0', score_5: '>=4.0', sort_order: 8 },
  ],
  waitress: [
    { item_key: 'checklist_completion', item_name: 'Checklist Harian - Completion Rate', target: '>=90%', contribution: 15, cara_penilaian: 'Auto dari daily_checklists (shift yang ditugaskan)', source_type: 'auto_checklist', score_1: '<60%', score_2: '<70%', score_3: '<80%', score_4: '<90%', score_5: '>=90%', sort_order: 1 },
    { item_key: 'kualitas_pelayanan', item_name: 'Kualitas Pelayanan', target: 'Sesuai SOP', contribution: 25, cara_penilaian: 'Penilaian Head Store (greeting, speed, attitude)', source_type: 'manual', score_1: 'Tidak sesuai SOP', score_2: 'Kadang tidak sesuai', score_3: 'Cukup sesuai', score_4: 'Sesuai', score_5: 'Sangat sesuai', sort_order: 2 },
    { item_key: 'kebersihan_area', item_name: 'Kebersihan Area & Meja', target: 'Bersih & Rapi', contribution: 20, cara_penilaian: 'Penilaian Head Store / Audit DM', source_type: 'manual', score_1: 'Sangat kotor', score_2: 'Kotor', score_3: 'Cukup bersih', score_4: 'Bersih', score_5: 'Sangat bersih & rapi', sort_order: 3 },
    { item_key: 'complain_handling', item_name: 'Complain Handling', target: '0 komplain', contribution: 15, cara_penilaian: 'Jumlah komplain pelanggan per bulan', source_type: 'manual', score_1: '>3 komplain', score_2: '3 komplain', score_3: '2 komplain', score_4: '1 komplain', score_5: '0 komplain', sort_order: 4 },
    { item_key: 'kedisiplinan', item_name: 'Kedisiplinan & Kehadiran', target: '>=95%', contribution: 10, cara_penilaian: 'Data absensi / catatan Head Store', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=95%', sort_order: 5 },
    { item_key: 'peer_review_360', item_name: 'Penilaian 360° Rekan Kerja', target: '>=4.0', contribution: 15, cara_penilaian: 'Rata-rata skor dari rekan kerja satu toko (anonim)', source_type: 'auto_360', score_1: '<2.0', score_2: '<2.5', score_3: '<3.0', score_4: '<4.0', score_5: '>=4.0', sort_order: 6 },
  ],
  asst_head_store: [
    { item_key: 'checklist_monitoring', item_name: 'Checklist Monitoring Toko', target: '>=90%', contribution: 8, cara_penilaian: 'Auto: rata-rata completion rate semua staff toko', source_type: 'auto_checklist', score_1: '<60%', score_2: '<70%', score_3: '<80%', score_4: '<90%', score_5: '>=90%', sort_order: 1 },
    { item_key: 'prep_monitoring', item_name: 'Preparation Monitoring Toko', target: '>=90%', contribution: 8, cara_penilaian: 'Auto: rata-rata completion rate preparation semua shift', source_type: 'auto_preparation', score_1: '<60%', score_2: '<70%', score_3: '<80%', score_4: '<90%', score_5: '>=90%', sort_order: 2 },
    { item_key: 'pencapaian_sales', item_name: 'Pencapaian Sales KPI Toko', target: '100%', contribution: 20, cara_penilaian: 'Target Sales Daily Tercapai (dari KPI Toko)', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=100%', sort_order: 3 },
    { item_key: 'coaching_briefing', item_name: 'Coaching & Briefing Staff', target: '>=4 sesi/bulan', contribution: 13, cara_penilaian: 'Jumlah sesi coaching terdokumentasi (LOG)', source_type: 'manual', score_1: '0 sesi', score_2: '1 sesi', score_3: '2 sesi', score_4: '3 sesi', score_5: '>=4 sesi', sort_order: 4 },
    { item_key: 'stock_fifo', item_name: 'Stock Accuracy & FIFO', target: 'FIFO & Cukup', contribution: 13, cara_penilaian: 'Audit Head Store / DM Mingguan', source_type: 'manual', score_1: 'Tidak FIFO & Kosong', score_2: 'Tidak FIFO & Banyak', score_3: 'Tidak FIFO & Cukup', score_4: 'FIFO & Kurang', score_5: 'FIFO & Cukup', sort_order: 5 },
    { item_key: 'opex_control', item_name: 'Opex Control', target: '<=3%', contribution: 10, cara_penilaian: 'Deviasi OPEX vs Budget', source_type: 'manual', score_1: '>4.5%', score_2: '>4%', score_3: '>3.5%', score_4: '>3%', score_5: '<=3%', sort_order: 6 },
    { item_key: 'sop_kebersihan', item_name: 'SOP & Kebersihan Toko', target: 'Baik', contribution: 8, cara_penilaian: 'Penilaian Head Store / Audit DM', source_type: 'manual', score_1: 'Sangat kurang', score_2: 'Kurang', score_3: 'Cukup', score_4: 'Baik', score_5: 'Sangat baik', sort_order: 7 },
    { item_key: 'kedisiplinan', item_name: 'Kedisiplinan & Kehadiran', target: '>=95%', contribution: 10, cara_penilaian: 'Data absensi / catatan Head Store', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=95%', sort_order: 8 },
    { item_key: 'peer_review_360', item_name: 'Penilaian 360° Rekan Kerja', target: '>=4.0', contribution: 10, cara_penilaian: 'Rata-rata skor dari rekan kerja satu toko (anonim)', source_type: 'auto_360', score_1: '<2.0', score_2: '<2.5', score_3: '<3.0', score_4: '<4.0', score_5: '>=4.0', sort_order: 9 },
  ],
  head_store: [
    { item_key: 'daily_target_briefing', item_name: 'Daily Target Briefing & Shift Brief', target: '100%', contribution: 5, cara_penilaian: 'Video ke DM', source_type: 'manual', score_1: 'Tidak pernah', score_2: 'Jarang', score_3: 'Kadang', score_4: 'Hampir selalu', score_5: 'Selalu lengkap', sort_order: 1 },
    { item_key: 'avg_transaction_attach_rate', item_name: 'Monitoring AVG Transaction & Attach Rate', target: '100%', contribution: 5, cara_penilaian: 'Buat laporan setiap hari ke DM', source_type: 'manual', score_1: 'Tidak ada laporan', score_2: 'Laporan sangat jarang', score_3: 'Laporan kadang masuk', score_4: 'Laporan hampir rutin', score_5: 'Laporan rutin setiap hari', sort_order: 2 },
    { item_key: 'achievement_sales_kpi_store', item_name: 'Achievement Sales KPI Store', target: '100%', contribution: 40, cara_penilaian: 'Target sales daily tercapai', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=100%', sort_order: 3 },
    { item_key: 'hpp_control', item_name: 'HPP Control', target: '47.00%', contribution: 5, cara_penilaian: 'HPP Finance', source_type: 'manual', score_1: '>52%', score_2: '>50%', score_3: '>49%', score_4: '>47%', score_5: '<=47%', sort_order: 4 },
    { item_key: 'waste_spoil_monitoring', item_name: 'Waste & Spoil Monitoring', target: '100%', contribution: 2.5, cara_penilaian: 'LOG lengkap', source_type: 'manual', score_1: 'Tidak ada log', score_2: 'Log banyak bolong', score_3: 'Log cukup lengkap', score_4: 'Log hampir lengkap', score_5: 'Log lengkap & rapi', sort_order: 5 },
    { item_key: 'stock_accuracy_fifo', item_name: 'Stock Accuracy & FIFO', target: '100%', contribution: 2.5, cara_penilaian: 'Audit DM mingguan', source_type: 'manual', score_1: 'Tidak FIFO & banyak selisih', score_2: 'Sering tidak FIFO', score_3: 'Cukup sesuai', score_4: 'FIFO dengan selisih kecil', score_5: 'FIFO & akurat', sort_order: 6 },
    { item_key: 'opex_control', item_name: 'Opex', target: '3%', contribution: 2.5, cara_penilaian: 'Deviasi vs budget', source_type: 'manual', score_1: '>5%', score_2: '>4.5%', score_3: '>4%', score_4: '>3%', score_5: '<=3%', sort_order: 7 },
    { item_key: 'coaching_log_staff', item_name: 'Coaching LOG Staff', target: '50%', contribution: 5, cara_penilaian: 'Coaching 1-1', source_type: 'manual', score_1: '0%', score_2: '<20%', score_3: '<35%', score_4: '<50%', score_5: '>=50%', sort_order: 8 },
    { item_key: 'training_execution', item_name: 'Training Execution', target: '100%', contribution: 5, cara_penilaian: 'Training by modul', source_type: 'manual', score_1: 'Tidak berjalan', score_2: 'Jarang jalan', score_3: 'Cukup jalan', score_4: 'Hampir semua modul', score_5: 'Semua modul berjalan', sort_order: 9 },
    { item_key: 'staff_discipline_attendance', item_name: 'Staff Discipline & Attendance', target: '100%', contribution: 2.5, cara_penilaian: 'Sesuai SOP HR', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=95%', sort_order: 10 },
    { item_key: 'audit_score', item_name: 'Audit Score', target: '90%', contribution: 10, cara_penilaian: 'Sesuai SOP audit', source_type: 'manual', score_1: '<75%', score_2: '<80%', score_3: '<85%', score_4: '<90%', score_5: '>=90%', sort_order: 11 },
    { item_key: 'sop_cleanliness', item_name: 'SOP & Cleanliness', target: '100%', contribution: 5, cara_penilaian: 'Audit DM mingguan', source_type: 'manual', score_1: 'Sangat kurang', score_2: 'Kurang', score_3: 'Cukup', score_4: 'Baik', score_5: 'Sangat baik', sort_order: 12 },
    { item_key: 'retention', item_name: 'Retention', target: '5.00%', contribution: 5, cara_penilaian: 'Staff yang resign', source_type: 'manual', score_1: '>12%', score_2: '>10%', score_3: '>8%', score_4: '>5%', score_5: '<=5%', sort_order: 13 },
    { item_key: 'complaint_handling_sla', item_name: 'Complain Handling SLA', target: '3x24 Jam', contribution: 5, cara_penilaian: 'Admin CS', source_type: 'manual', score_1: '>5x24 jam', score_2: '>4x24 jam', score_3: '>3x24 jam', score_4: '<=3x24 jam namun tidak konsisten', score_5: '<=3x24 jam konsisten', sort_order: 14 },
  ],
  district_manager: [
    { item_key: 'store_achieve_kpi_sales', item_name: '% Store Achieve KPI Sales', target: '100%', contribution: 40, cara_penilaian: 'KPI Store', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=100%', sort_order: 1 },
    { item_key: 'avg_sales_attach_rate_district', item_name: 'AVG Sales & Attach Rate District', target: '100%', contribution: 10, cara_penilaian: 'vs target', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=100%', sort_order: 2 },
    { item_key: 'head_store_kpi_achievement', item_name: '% Head Store KPI Achievement', target: '100%', contribution: 10, cara_penilaian: 'KPI Head Store', source_type: 'manual', score_1: '<80%', score_2: '<85%', score_3: '<90%', score_4: '<95%', score_5: '>=100%', sort_order: 3 },
    { item_key: 'head_store_coaching', item_name: 'Head Store Coaching', target: '100%', contribution: 5, cara_penilaian: 'Coaching LOG', source_type: 'manual', score_1: 'Tidak ada coaching', score_2: 'Jarang coaching', score_3: 'Cukup coaching', score_4: 'Rutin coaching', score_5: 'Rutin & berkualitas', sort_order: 4 },
    { item_key: 'head_store_discipline_compliance', item_name: 'Head Store Discipline & Compliance', target: '100%', contribution: 5, cara_penilaian: 'Major issue', source_type: 'manual', score_1: 'Sering issue mayor', score_2: 'Ada beberapa issue mayor', score_3: 'Issue masih berulang', score_4: 'Hanya issue minor', score_5: 'Patuh & tanpa issue mayor', sort_order: 5 },
    { item_key: 'avg_hpp_district', item_name: 'AVG HPP District', target: '47.50%', contribution: 5, cara_penilaian: 'HPP Finance', source_type: 'manual', score_1: '>52%', score_2: '>50%', score_3: '>49%', score_4: '>47.5%', score_5: '<=47.5%', sort_order: 6 },
    { item_key: 'audit_pass_rate', item_name: 'Audit Pass Rate', target: '90%', contribution: 5, cara_penilaian: 'Audit', source_type: 'manual', score_1: '<75%', score_2: '<80%', score_3: '<85%', score_4: '<90%', score_5: '>=90%', sort_order: 7 },
    { item_key: 'complaint_closure_sla', item_name: 'Complaint Closure SLA', target: '3x24Jam', contribution: 5, cara_penilaian: '<SLA', source_type: 'manual', score_1: 'Banyak lewat SLA', score_2: 'Sering lewat SLA', score_3: 'Sebagian lewat SLA', score_4: 'Mayoritas sesuai SLA', score_5: 'Semua sesuai SLA', sort_order: 8 },
    { item_key: 'store_visit_coverage', item_name: 'Store Visit Coverage', target: '100%', contribution: 10, cara_penilaian: 'Visit log', source_type: 'manual', score_1: '<70%', score_2: '<80%', score_3: '<90%', score_4: '<100%', score_5: '100%', sort_order: 9 },
    { item_key: 'action_plan_closure', item_name: 'Action Plan Closure', target: '100%', contribution: 5, cara_penilaian: 'Head Store follow up', source_type: 'manual', score_1: '<70%', score_2: '<80%', score_3: '<90%', score_4: '<100%', score_5: '100%', sort_order: 10 },
  ],
}

export function getDefault360Items(groupType) {
  return (DEFAULT_KPI_360_ITEMS[groupType] || []).map((item) => ({ ...item, is_active: true, group_type: groupType }))
}

export function getDefaultPersonalItems(role) {
  return (DEFAULT_KPI_PERSONAL_ITEMS[role] || []).map((item) => ({ ...item, role, is_active: true }))
}
