-- ============================================================
-- Seed KPI Personal items for Head Store and District Manager
-- Migration 015
-- ============================================================

ALTER TABLE kpi_personal_items
  ALTER COLUMN contribution TYPE NUMERIC(5,2);

INSERT INTO kpi_personal_items
  (role, item_key, item_name, target, contribution, cara_penilaian, source_type,
   score_1, score_2, score_3, score_4, score_5, sort_order)
VALUES
  ('head_store','daily_target_briefing','Daily Target Briefing & Shift Brief','100%',5,
   'Video ke DM','manual',
   'Tidak pernah','Jarang','Kadang','Hampir selalu','Selalu lengkap',1),
  ('head_store','avg_transaction_attach_rate','Monitoring AVG Transaction & Attach Rate','100%',5,
   'Buat laporan setiap hari ke DM','manual',
   'Tidak ada laporan','Laporan sangat jarang','Laporan kadang masuk','Laporan hampir rutin','Laporan rutin setiap hari',2),
  ('head_store','achievement_sales_kpi_store','Achievement Sales KPI Store','100%',40,
   'Target sales daily tercapai','manual',
   '<80%','<85%','<90%','<95%','>=100%',3),
  ('head_store','hpp_control','HPP Control','47.00%',5,
   'HPP Finance','manual',
   '>52%','>50%','>49%','>47%','<=47%',4),
  ('head_store','waste_spoil_monitoring','Waste & Spoil Monitoring','100%',2.5,
   'LOG lengkap','manual',
   'Tidak ada log','Log banyak bolong','Log cukup lengkap','Log hampir lengkap','Log lengkap & rapi',5),
  ('head_store','stock_accuracy_fifo','Stock Accuracy & FIFO','100%',2.5,
   'Audit DM mingguan','manual',
   'Tidak FIFO & banyak selisih','Sering tidak FIFO','Cukup sesuai','FIFO dengan selisih kecil','FIFO & akurat',6),
  ('head_store','opex_control','Opex','3%',2.5,
   'Deviasi vs budget','manual',
   '>5%','>4.5%','>4%','>3%','<=3%',7),
  ('head_store','coaching_log_staff','Coaching LOG Staff','50%',5,
   'Coaching 1-1','manual',
   '0%','<20%','<35%','<50%','>=50%',8),
  ('head_store','training_execution','Training Execution','100%',5,
   'Training by modul','manual',
   'Tidak berjalan','Jarang jalan','Cukup jalan','Hampir semua modul','Semua modul berjalan',9),
  ('head_store','staff_discipline_attendance','Staff Discipline & Attendance','100%',2.5,
   'Sesuai SOP HR','manual',
   '<80%','<85%','<90%','<95%','>=95%',10),
  ('head_store','audit_score','Audit Score','90%',10,
   'Sesuai SOP audit','manual',
   '<75%','<80%','<85%','<90%','>=90%',11),
  ('head_store','sop_cleanliness','SOP & Cleanliness','100%',5,
   'Audit DM mingguan','manual',
   'Sangat kurang','Kurang','Cukup','Baik','Sangat baik',12),
  ('head_store','retention','Retention','5.00%',5,
   'Staff yang resign','manual',
   '>12%','>10%','>8%','>5%','<=5%',13),
  ('head_store','complaint_handling_sla','Complain Handling SLA','3x24 Jam',5,
   'Admin CS','manual',
   '>5x24 jam','>4x24 jam','>3x24 jam','<=3x24 jam namun tidak konsisten','<=3x24 jam konsisten',14),

  ('district_manager','store_achieve_kpi_sales','% Store Achieve KPI Sales','100%',40,
   'KPI Store','manual',
   '<80%','<85%','<90%','<95%','>=100%',1),
  ('district_manager','avg_sales_attach_rate_district','AVG Sales & Attach Rate District','100%',10,
   'vs target','manual',
   '<80%','<85%','<90%','<95%','>=100%',2),
  ('district_manager','head_store_kpi_achievement','% Head Store KPI Achievement','100%',10,
   'KPI Head Store','manual',
   '<80%','<85%','<90%','<95%','>=100%',3),
  ('district_manager','head_store_coaching','Head Store Coaching','100%',5,
   'Coaching LOG','manual',
   'Tidak ada coaching','Jarang coaching','Cukup coaching','Rutin coaching','Rutin & berkualitas',4),
  ('district_manager','head_store_discipline_compliance','Head Store Discipline & Compliance','100%',5,
   'Major issue','manual',
   'Sering issue mayor','Ada beberapa issue mayor','Issue masih berulang','Hanya issue minor','Patuh & tanpa issue mayor',5),
  ('district_manager','avg_hpp_district','AVG HPP District','47.50%',5,
   'HPP Finance','manual',
   '>52%','>50%','>49%','>47.5%','<=47.5%',6),
  ('district_manager','audit_pass_rate','Audit Pass Rate','90%',5,
   'Audit','manual',
   '<75%','<80%','<85%','<90%','>=90%',7),
  ('district_manager','complaint_closure_sla','Complaint Closure SLA','3x24Jam',5,
   '<SLA','manual',
   'Banyak lewat SLA','Sering lewat SLA','Sebagian lewat SLA','Mayoritas sesuai SLA','Semua sesuai SLA',8),
  ('district_manager','store_visit_coverage','Store Visit Coverage','100%',10,
   'Visit log','manual',
   '<70%','<80%','<90%','<100%','100%',9),
  ('district_manager','action_plan_closure','Action Plan Closure','100%',5,
   'Head Store follow up','manual',
   '<70%','<80%','<90%','<100%','100%',10)
ON CONFLICT (role, item_key) DO UPDATE
SET
  item_name = EXCLUDED.item_name,
  target = EXCLUDED.target,
  contribution = EXCLUDED.contribution,
  cara_penilaian = EXCLUDED.cara_penilaian,
  source_type = EXCLUDED.source_type,
  score_1 = EXCLUDED.score_1,
  score_2 = EXCLUDED.score_2,
  score_3 = EXCLUDED.score_3,
  score_4 = EXCLUDED.score_4,
  score_5 = EXCLUDED.score_5,
  is_active = true,
  sort_order = EXCLUDED.sort_order;
